Repository markcyen/viewing_party, pull requests merged in 2021-07, with the labels that each got.

#20 Db setup
  .travis.yml
  Gemfile
  Gemfile.lock
  app/models/friendship.rb
  app/models/invitation.rb
  app/models/party.rb
  app/models/user.rb
  db/migrate/20210706203752_create_users.rb
  db/migrate/20210706205707_create_friendships.rb
  db/migrate/20210707203435_create_parties.rb
  db/migrate/20210707205804_create_invitations.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/friendship_spec.rb
  spec/models/invitation_spec.rb
  spec/models/party_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: documentation

#22 Welcome page
  app/controllers/welcome_controller.rb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/welcome/index_spec.rb
  spec/rails_helper.rb
Labels: Core

#23 Registration page
  app/controllers/dashboard_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/dashboard/index.html.erb
  app/views/layouts/application.html.erb
  app/views/users/new.html.erb
  config/routes.rb
  db/migrate/20210706203752_create_users.rb
  db/schema.rb
  spec/features/registration_spec.rb
Labels: Core, enhancement

#25 Minor refactoring
  app/assets/images/schema.jpg
  app/controllers/dashboard_controller.rb
  app/controllers/users_controller.rb
  app/controllers/welcome_controller.rb
  app/models/friendship.rb
  app/models/invitation.rb
  app/models/party.rb
  app/models/user.rb
  app/views/dashboard/index.html.erb
  app/views/users/new.html.erb
  app/views/welcome/index.html.erb
  spec/features/registration_spec.rb
  spec/features/welcome/index_spec.rb
  spec/models/friendship_spec.rb
  spec/models/invitation_spec.rb
  spec/models/party_spec.rb
  spec/models/user_spec.rb
Labels: chore, documentation

#26 Thursday
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/views/dashboard/index.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/login_spec.rb
Labels: Core, documentation, enhancement

#27 Add status column to invitation table
  app/models/invitation.rb
  db/migrate/20210709002830_add_column.rb
  db/schema.rb
Labels: chore, enhancement

#28 Main dashboard
  app/views/dashboard/index.html.erb
  spec/features/dashboard/index_spec.rb
Labels: Core

#29 movie discover test, show and controller
  app/controllers/discover_controller.rb
  app/views/dashboard/index.html.erb
  app/views/discover/show.html.erb
  config/routes.rb
  spec/features/dashboard/discover_spec.rb
  spec/features/dashboard/index_spec.rb
Labels: Core

#30 Dashboard friends
  app/controllers/dashboard_controller.rb
  app/controllers/friends_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/models/application_record.rb
  app/views/dashboard/index.html.erb
  config/routes.rb
  spec/features/dashboard/index_spec.rb
  spec/features/registration_spec.rb
Labels: Core, paired commit

#31 Saturday
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/movies_controller.rb
  app/views/discover/show.html.erb
  app/views/movies/index.html.erb
  config/routes.rb
  spec/features/movies/index_spec.rb
  spec/fixtures/top_movies.json
  spec/spec_helper.rb
Labels: Core

#32 Movies search
  app/controllers/movies_controller.rb
  app/views/discover/show.html.erb
  app/views/movies/index.html.erb
  spec/features/movies/index_spec.rb
  spec/fixtures/search_movies.json
  spec/fixtures/top_movies_1.json
  spec/fixtures/top_movies_2.json
Labels: API consumption, Core, paired commit

#33 Refactor controller
  app/controllers/dashboard_controller.rb
  app/controllers/movies_controller.rb
  app/controllers/users_controller.rb
  app/facades/movie_facade.rb
  app/poros/movie.rb
  app/services/movie_service.rb
  app/views/movies/index.html.erb
  app/views/users/new.html.erb
  config/routes.rb
  spec/facades/movie_facade_spec.rb
  spec/features/movies/index_spec.rb
  spec/features/registration_spec.rb
  spec/fixtures/search_movies_1.json
  spec/fixtures/search_movies_2.json
  spec/fixtures/top_movies_1.json
  spec/fixtures/top_movies_2.json
  spec/poros/movie_spec.rb
  spec/services/movie_service_spec.rb
  spec/spec_helper.rb
Labels: API consumption, Core, documentation, enhancement

#35 Movies show page
  app/controllers/movies_controller.rb
  app/facades/movie_facade.rb
  app/poros/movie.rb
  app/services/movie_service.rb
  app/views/movies/index.html.erb
  app/views/movies/show.html.erb
  config/routes.rb
  spec/features/movies/index_spec.rb
  spec/features/movies/show_spec.rb
  spec/fixtures/shawshank_cast.json
  spec/fixtures/shawshank_details.json
  spec/fixtures/shawshank_reviews.json
  spec/spec_helper.rb
Labels: API consumption, Core

#36 Wednesday
  app/controllers/dashboard_controller.rb
  app/views/dashboard/index.html.erb
  spec/features/dashboard/index_spec.rb
Labels: Core, bug

#37 Refactor API consumption of movies
  app/views/dashboard/index.html.erb
  app/views/discover/show.html.erb
  app/views/movies/show.html.erb
  spec/features/dashboard/index_spec.rb
  spec/features/movies/show_spec.rb
Labels: API consumption, Core
